name: build

on:
  pull_request:
    paths: ['src/**', 'include/**', '.github/workflows/build.yaml']
  push:
    branches: [ master ]
    paths: ['src/**', 'include/**', '.github/workflows/build.yaml']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false # We want results from all OSes even if one fails.
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            build_command: make build ARCH=x64-modern COMP=gcc OS=linux
          - os: macos-latest
            build_command: make build ARCH=armv8.5-a COMP=clang OS=osx

    steps:
    - uses: actions/checkout@v4

    - name: build
      run: |-
        mkdir -p bin
        cd src
        ${{ matrix.build_command }}

    - uses: actions/upload-artifact@v4
      with:
        name: artifact_${{ runner.os }}
        path: bin

  windows-build:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    - name: build
      run: |-
        mkdir -p bin
        cd src
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        nmake -fnmakefile vc-w64-modern
      shell: cmd

    - uses: actions/upload-artifact@v4
      with:
        name: artifact_${{ runner.os }}
        path: bin
